//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.17 at 10:38:20 PM EET 
//


package com.github.tsungviewer.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}arrivalphase"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "arrivalphase"
})
@XmlRootElement(name = "load")
public class Load {

    @XmlElement(required = true)
    protected Arrivalphase arrivalphase;

    /**
     * Gets the value of the arrivalphase property.
     * 
     * @return
     *     possible object is
     *     {@link Arrivalphase }
     *     
     */
    public Arrivalphase getArrivalphase() {
        return arrivalphase;
    }

    /**
     * Sets the value of the arrivalphase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Arrivalphase }
     *     
     */
    public void setArrivalphase(Arrivalphase value) {
        this.arrivalphase = value;
    }

}
