//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.27 at 10:06:37 PM EEST 
//


package com.github.wfviewer.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}Deprecated"/>
 *         &lt;element ref="{}Description"/>
 *         &lt;element ref="{}FieldMapping"/>
 *         &lt;element ref="{}FieldSetRef"/>
 *         &lt;element ref="{}FieldUIComponents"/>
 *         &lt;element ref="{}GroupRef"/>
 *         &lt;element ref="{}Property"/>
 *         &lt;element ref="{}Type"/>
 *         &lt;element ref="{}cracking"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deprecated",
    "description",
    "fieldMapping",
    "fieldSetRef",
    "fieldUIComponents",
    "groupRef",
    "property",
    "type",
    "cracking"
})
@XmlRootElement(name = "FieldDef")
public class FieldDef {

    @XmlElement(name = "Deprecated")
    protected Deprecated deprecated;
    @XmlElement(name = "Description")
    protected Description description;
    @XmlElement(name = "FieldMapping")
    protected FieldMapping fieldMapping;
    @XmlElement(name = "FieldSetRef")
    protected FieldSetRef fieldSetRef;
    @XmlElement(name = "FieldUIComponents")
    protected FieldUIComponents fieldUIComponents;
    @XmlElement(name = "GroupRef")
    protected GroupRef groupRef;
    @XmlElement(name = "Property")
    protected Property property;
    @XmlElement(name = "Type")
    protected Type type;
    protected Cracking cracking;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String name;

    /**
     * Gets the value of the deprecated property.
     * 
     * @return
     *     possible object is
     *     {@link Deprecated }
     *     
     */
    public Deprecated getDeprecated() {
        return deprecated;
    }

    /**
     * Sets the value of the deprecated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Deprecated }
     *     
     */
    public void setDeprecated(Deprecated value) {
        this.deprecated = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the fieldMapping property.
     * 
     * @return
     *     possible object is
     *     {@link FieldMapping }
     *     
     */
    public FieldMapping getFieldMapping() {
        return fieldMapping;
    }

    /**
     * Sets the value of the fieldMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldMapping }
     *     
     */
    public void setFieldMapping(FieldMapping value) {
        this.fieldMapping = value;
    }

    /**
     * Gets the value of the fieldSetRef property.
     * 
     * @return
     *     possible object is
     *     {@link FieldSetRef }
     *     
     */
    public FieldSetRef getFieldSetRef() {
        return fieldSetRef;
    }

    /**
     * Sets the value of the fieldSetRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldSetRef }
     *     
     */
    public void setFieldSetRef(FieldSetRef value) {
        this.fieldSetRef = value;
    }

    /**
     * Gets the value of the fieldUIComponents property.
     * 
     * @return
     *     possible object is
     *     {@link FieldUIComponents }
     *     
     */
    public FieldUIComponents getFieldUIComponents() {
        return fieldUIComponents;
    }

    /**
     * Sets the value of the fieldUIComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldUIComponents }
     *     
     */
    public void setFieldUIComponents(FieldUIComponents value) {
        this.fieldUIComponents = value;
    }

    /**
     * Gets the value of the groupRef property.
     * 
     * @return
     *     possible object is
     *     {@link GroupRef }
     *     
     */
    public GroupRef getGroupRef() {
        return groupRef;
    }

    /**
     * Sets the value of the groupRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupRef }
     *     
     */
    public void setGroupRef(GroupRef value) {
        this.groupRef = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * @return
     *     possible object is
     *     {@link Property }
     *     
     */
    public Property getProperty() {
        return property;
    }

    /**
     * Sets the value of the property property.
     * 
     * @param value
     *     allowed object is
     *     {@link Property }
     *     
     */
    public void setProperty(Property value) {
        this.property = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Type }
     *     
     */
    public Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Type }
     *     
     */
    public void setType(Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the cracking property.
     * 
     * @return
     *     possible object is
     *     {@link Cracking }
     *     
     */
    public Cracking getCracking() {
        return cracking;
    }

    /**
     * Sets the value of the cracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cracking }
     *     
     */
    public void setCracking(Cracking value) {
        this.cracking = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
