//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.27 at 10:06:37 PM EEST 
//


package com.github.wfviewer.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}actions" maxOccurs="unbounded"/>
 *         &lt;element ref="{}UI"/>
 *         &lt;element ref="{}BusinessLogics"/>
 *         &lt;element ref="{}DocFieldsDef"/>
 *         &lt;element ref="{}IDL_TypeMapping"/>
 *         &lt;element ref="{}ExpertSystem"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="lastupdate" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "actions",
    "ui",
    "businessLogics",
    "docFieldsDef",
    "idlTypeMapping",
    "expertSystem"
})
@XmlRootElement(name = "icc-config")
public class IccConfig {

    @XmlElement(required = true)
    protected List<Actions> actions;
    @XmlElement(name = "UI", required = true)
    protected UI ui;
    @XmlElement(name = "BusinessLogics", required = true)
    protected BusinessLogics businessLogics;
    @XmlElement(name = "DocFieldsDef", required = true)
    protected DocFieldsDef docFieldsDef;
    @XmlElement(name = "IDL_TypeMapping", required = true)
    protected IDLTypeMapping idlTypeMapping;
    @XmlElement(name = "ExpertSystem", required = true)
    protected ExpertSystem expertSystem;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String version;
    @XmlAttribute(required = true)
    protected String lastupdate;

    /**
     * Gets the value of the actions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Actions }
     * 
     * 
     */
    public List<Actions> getActions() {
        if (actions == null) {
            actions = new ArrayList<Actions>();
        }
        return this.actions;
    }

    /**
     * Gets the value of the ui property.
     * 
     * @return
     *     possible object is
     *     {@link UI }
     *     
     */
    public UI getUI() {
        return ui;
    }

    /**
     * Sets the value of the ui property.
     * 
     * @param value
     *     allowed object is
     *     {@link UI }
     *     
     */
    public void setUI(UI value) {
        this.ui = value;
    }

    /**
     * Gets the value of the businessLogics property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessLogics }
     *     
     */
    public BusinessLogics getBusinessLogics() {
        return businessLogics;
    }

    /**
     * Sets the value of the businessLogics property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessLogics }
     *     
     */
    public void setBusinessLogics(BusinessLogics value) {
        this.businessLogics = value;
    }

    /**
     * Gets the value of the docFieldsDef property.
     * 
     * @return
     *     possible object is
     *     {@link DocFieldsDef }
     *     
     */
    public DocFieldsDef getDocFieldsDef() {
        return docFieldsDef;
    }

    /**
     * Sets the value of the docFieldsDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocFieldsDef }
     *     
     */
    public void setDocFieldsDef(DocFieldsDef value) {
        this.docFieldsDef = value;
    }

    /**
     * Gets the value of the idlTypeMapping property.
     * 
     * @return
     *     possible object is
     *     {@link IDLTypeMapping }
     *     
     */
    public IDLTypeMapping getIDLTypeMapping() {
        return idlTypeMapping;
    }

    /**
     * Sets the value of the idlTypeMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDLTypeMapping }
     *     
     */
    public void setIDLTypeMapping(IDLTypeMapping value) {
        this.idlTypeMapping = value;
    }

    /**
     * Gets the value of the expertSystem property.
     * 
     * @return
     *     possible object is
     *     {@link ExpertSystem }
     *     
     */
    public ExpertSystem getExpertSystem() {
        return expertSystem;
    }

    /**
     * Sets the value of the expertSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpertSystem }
     *     
     */
    public void setExpertSystem(ExpertSystem value) {
        this.expertSystem = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the lastupdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastupdate() {
        return lastupdate;
    }

    /**
     * Sets the value of the lastupdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastupdate(String value) {
        this.lastupdate = value;
    }

}
